@ECHO OFF
COLOR 0B
MODE CON COLS=300 LINES=3000
TITLE KODI REPO GENERATOR COPYRIGHT (C) 2019 BY LOKI1979

SET SCRIPT_LOCATION=%~dp0
SET PYTHON="%SCRIPT_LOCATION%python\python.exe"
SET SCRIPT="%SCRIPT_LOCATION%repository\generator.py"
%PYTHON% %SCRIPT%

@ECHO   
PAUSE